config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create] do
    collection do
      get   :edit
      patch :update
    end
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  patch "/questions/:id/lock" => "questions#lock", as: :lock_question
  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  get "/hello" => "welcome#index"

  get "/contact" => "contact#index"
  post "/contact" => "contact#create"

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/hello/:name" => "welcome#hello", as: :greet

  get "/hello/:name/:city" => "welcome#hello", as: :full_greeting

  root "welcome#index"

end

app/models/question.rb
class Question < ActiveRecord::Base

  #  has_many :answers assumes that you have a model Answer that has a reference
  # to theis model (Question) called question_id (Integer)
  # the dependent option is needed because we've added a foreign key Contraint
  # to our database so the dependent records (in this case answers) must do
  # something before deleting a question that they reference. the options are:
  # :destroy -> will delete all the answers referencing this question before
  #             deleting the question
  # :nullify -> will make question_id field null in the database before deleting
  #             the quesiton
  has_many :answers, dependent: :destroy
  has_many :comments, through: :answers

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  belongs_to :category

  belongs_to :user

  mount_uploader :image, ImageUploader

  # this prevents the record from saving or updating unless a title is provided
  validates :title, presence:   {message: "must be present"},
                    # this will check for the uniqueness of the tite/body
                    # combination. So title doesn't have to be unique by itself
                    # but the combination with body should.
                    uniqueness: {scope: :body},
                    length:     {minimum: 3} # title must have at least 3 chars

  validates(:body, {presence: true})

  # numericality validates that the provided field is a number you can give it:
  # greater_than, greater_than_or_equal_to, less_than, less_than_or_equal_to
  validates :view_count, presence:     true,
                         numericality: {greater_than_or_equal_to: 0}

  # if you had an email attribute you can validate the format of the attribute
  # using the `format` option, it takes a regular expression
  # validates :email, format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  # we use validate if we want to have a custom validation method that we can
  # have any kind of Ruby code in.
  validate :no_monkey

  after_initialize :set_defaults

  before_save :capitalize_title

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  # def to_param
  #   "#{id}-#{title}".parameterize
  # end

  scope :recent, lambda { order(:created_at).reverse_order }
  scope :recent, -> { order(:created_at).reverse_order }
  def self.recent
    order(:created_at).reverse_order
  end

  def self.ten
    limit(10)
  end

  def self.recent_ten
    recent.ten
  end

  def self.search(item)
    # thing = "%#{item}%"
    # where(["title ILIKE ? OR body ILIKE ?", thing, thing])

    search_term = "%#{item}%"
    # where("title || ' ' || body ILIKE ? ", search_term)
    where(["title ILIKE :term OR body ILIKE :term", {term: search_term}])
  end

  def self.search_multiple(words)
    query   = []
    terms   = []
    words.split.each do |word|
      search_term   = "%#{word}%"
      terms << search_term
      terms << search_term
      query << "title ILIKE ? OR body ILIKE ?"
    end
    where([query.join(" OR ")] + terms)
  end

  def user_name
    if user
      user.full_name
    else
      "Anonymous"
    end
  end

  # delegate :name, to: :category # @question.name
  delegate :name, to: :category, prefix: true # @question.category_name
  # def category_name
  #   category.name
  # end

  def like_for(user)
    likes.find_by_user_id(user.id)
  end

  def favourite_for(user)
    favourites.find_by_user_id(user.id)
  end

  def votes_count
    votes.select {|v| v.up? }.count - votes.select {|v| v.down? }.count
  end

  private

  def no_monkey
    if title.present? && title.downcase.include?("monkey")
      # this will add to the errors object attached to the current object.
      # if the errors object is not an empty Hash then rails treats the
      # record as invalid
      errors.add(:title, "can't have monkey!")
    end
  end

  def set_defaults
    self.view_count ||= 0
  end

  def capitalize_title
    # self.title.capitalize!
    self.title = title.capitalize
  end

end



#
# module HandyMethods
#
#   def say_hello
#     puts "Hello There"
#   end
#
# end
#
# class Abc
#   include HandyMethods
#   # as if you did:
#   # def say_hello
#   #   puts "Hello There"
#   # end
# end
# # a = Abc.new
# # a.say_hello
#
# class Xyz
#   extend HandyMethods
#   # as if you did:
#   # def self.say_hello
#   #   puts "Hello There"
#   # end
# end
# # Xyz.say_hello

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]

  PER_PAGE = 10
  # the before action takes in a required first argument which references a method
  # that will be executed before every action. You can give it a second arguement
  # which is a hash, possible keys are :only and :except if you want to restrict
  # the method calls to specific actions
  # before_action :find_question, except: [:index, :new, :create]
  before_action :find_question, only: [:show, :edit, :update, :destroy, :lock]

  before_action :authorize!, only: [:edit, :update, :destroy]

  # the new action is the one that is used by convention in Rails to display
  # a form to create the record (in this case question record)
  def new
    # We instantiate an instance variable of the object we'd like to create in
    # order to use the `form_for` helper method in Rails to easily generate
    # a form that submits to the create action
    @question = Question.new # Question.new(title: "hello")
  end

  def create
    @question      = Question.new(question_params)
    @question.user = current_user
    Rails.logger.info ">>>>>"
    if @question.save
      # flash[:notice] = "Question created!"
      # passing :notice / :alert only works for redirect
      redirect_to question_path(@question), notice: "Question created!"
    else
      flash[:alert] = "See errors below"
      render :new
    end
  end

  # GET /questions/:id (e.g. /questions/1)
  # this is used to show a page with question information
  def show
    respond_to do |format|
      @answer = Answer.new
      format.html { render }
      format.json { render json: {question: @question, answers: @question.answers} }
      format.xml  { render xml: @question }
    end
  end

  # GET /questions
  # this is used to show a page with listing of all the questions in our DB
  def index
    per_page = params[:per_page] || PER_PAGE
    if params[:search]
      @questions = Question.search(params[:search]).order("#{params[:order]}").page(params[:page]).per(per_page)
    else
      @questions = Question.order("#{params[:order]}").page(params[:page]).per(per_page)
    end
    respond_to do |format|
      format.json { render json: @questions }
      format.html { render  }
    end
    # @question = Question.new
  end

  # GET /questions/:id/edit (e.g. /questions/123/edit )
  # this is used to show a form to edit and submit to update a question in the database
  def edit
  end

  # PATCH /questions/:id (e.g. /questions/123)
  # this is used to handle the submission of the question form from the edit page
  # when user is updating the information on a question
  def update
    @question.slug = nil
    # if updating the question is successful
    if @question.update question_params
      # redirecting to the question show page
      redirect_to question_path(@question)
    else
      # rendering the edit form so the user can see the errors
      render :edit
    end
  end

  # DELETE /questions/:id (e.g. /questions/123)
  # this is used to delete a question from the database
  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def lock
    # this toggles the value of locked between true and false
    @question.locked = !@question.locked
    @question.save
    redirect_to question_path(@question)
  end

  private

  def find_question
    @question = Question.friendly.find params[:id]
  end

  def authorize!
    # head :unauthorized unless can? :manage, @question
    redirect_to root_path, alert: "access denied" unless can? :manage, @question
  end

  def question_params
    # params[:question] => {title: "Abc", body: "xyz"}
    # params.require ensures that the params hash has a key :question and
    # fetches all the attributes from that hash. the .permit only allows
    # the parameters given to be mass-assigned
    # question_params = params.require(:question).permit([:title, :body])
    # question_params =>  {title: "Abc", body: "xyz"}
    params.require(:question).permit([:title, :body, :image,
                                     {tag_ids: []},
                                     :locked, :category_id])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for (@question || Question.new) , html: {class: "form-horizontal"} do |f| %>
  <%= f.input :title, hint: "don't put monkey" %>
  <%= f.input :body, input_html: {placeholder: "Give more details here"} %>
  <%= f.input :image %>
  <%= f.association :category, include_blank: false %>
  <%= f.association :tags, as: :check_boxes %>
  <div class="form-group">
    <%= f.button :submit, class: "btn-primary", data: {disable_with: "saving.."} %>
  </div>
<% end %>


<!-- <% @question ||= Question.new %>
<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%# the form_for helper method can take an ActiveRecord object as a first arguement
    for instance, @question which is of class Question.
    Rails, by convention, will do the following:
    1. If @question is not persisted in the database, it will make the action for
       the form `questions_path`. It will look for the class name of the passed
       object (in this case its Question) and by convention submit to questions_path.
       It will also make the method POST in this case. (New / Create)
    2. If @question is persisted to the database, it will make the action for
      the form go to question_path (/questions/:id) (where :id is the id of
      @question) and it will make the form submit a PATCH request in order for this
      form to submit to the update action in our controller. (Edit / Update)
    %>
<%= form_for @question , html: {class: "form-horizontal"} do |f| %>
  <%# if you don't pass any option for f.submit it will:
      1. If @question is not persisted it will make the button label "Create [Object Class]"
      2. If @question is persisted it will make the button label "Update [Object Class]" %>
  <div class="form-group">
    <%= f.label :title %>
    <%# using f.text_field ensures that Rails will use the proper `name` HTML
        attribute and it will also populate the text field with data if @question
        title has a value %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {},
                            {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn special-btn-primary", data: {disable_with: "saving.."} %>
  </div>
<% end %> -->
<!--
<form class="new_question" id="new_question" action="/questions" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="LSe9Xblfla1XasfnOzKfDuXvJEj8znZF+VOi8SLToy1NZEp/AO4008qqDLx7MOjZgStJ5fiGhYo/+TSK2Y4Oyg==">
  <input type="submit" name="commit" value="Create Question">
</form> -->

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_tag questions_path, method: :get do %>
      <%= search_field_tag :search, params[:search] %>
      <%= submit_tag "Search", class: "btn btn-primary btn-sm" %>
    <% end %>
  </div>
  <div class="col-md-6">
    <!-- Button trigger modal -->
    <div class=" text-right">
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        New Question
      </button>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Create New Question</h4>
          </div>
            <%= form_for Question.new , html: {class: "form-horizontal"} do |f| %>
              <div class="modal-body">
                <div class="col-md-12">
                  <%# if you don't pass any option for f.submit it will:
                      1. If @question is not persisted it will make the button label "Create [Object Class]"
                      2. If @question is persisted it will make the button label "Update [Object Class]" %>
                  <div class="form-group">
                    <%= f.label :title %>
                    <%# using f.text_field ensures that Rails will use the proper `name` HTML
                        attribute and it will also populate the text field with data if @question
                        title has a value %>
                    <%= f.text_field :title, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= f.label :category_id %>
                    <%= f.collection_select :category_id, Category.all, :id, :name, {},
                                            {class: "form-control"} %>
                  </div>
                  <div class="form-group">
                    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
                  </div>
                </div>
              </div>
              <div class="clearfix"></div>
              <div class="modal-footer">
                <div class="col-md-12">
                  <div class="form-group">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= f.submit class: "btn btn-primary", data: {disable_with: "saving.."} %>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<h1>All Questions</h1>
<%= link_to "order by title", questions_path(search: params[:search], order: "title") %>
<%= link_to "order by body", questions_path(search: params[:search], order: "body") %>
<% @questions.each do |q| %>
  <%#= link_to q.title, question_path({id: q.id}) %>
  <%#= link_to q.title, q %>
  <div>
    <%= link_to q.title, question_path(q) %>
  </div>
<% end %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<h1>Create a question</h1>

<%# render is going to look for a partial meaning a view file that starts with
    an `_` if you don't specify full path it will look in the same folder as
    this file's folder. In this case it will look in views/questions folder.
    You can specify full path such as: render "/questions/form"
    - Partial have access to instance varialbes so no need to pass them. For
      instance. the _form.html.erb partial have access to @question
    - If you want to pass local variables to partial then you can pass them
      as a hash to the render method. e.g: render "form", greeting: "Hello"
     %>
<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<hr>
<p><%= @question.body %></p>
<p>View Count: <%= @question.view_count %></p>
<p>Category: <%= @question.category_name %></p>
<% if @question.image.present? %>
  <%= image_tag @question.image.url(:medium) %>
<% end %>
<!-- <p>Tags: <%= @question.tags.map(&:name).join(", ") %></p> -->
<p>Tags: <%= @question.tags.map {|x| x.name }.join(", ") %></p>
<p>Created by <%= @question.user_name %> on
                <%= formatted_date(@question.created_at) %></p>
<%# this link to the edit page of the question that shows a form to edit the values already saved %>
<% if can? :edit, @question %>
  <%= link_to "Edit", edit_question_path(@question), class: "btn btn-info" %>
<% end %>
<% if can? :destroy, @question %>
  <%= link_to "Delete", question_path(@question), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
<% end %>

<%= link_to (@question.locked ? "Lock" : "Un-lock"),
            question_path(@question, {question: {locked: !@question.locked}}),
            class: "btn btn-warning", method: :patch %>

<div class="col-md-3">
  <div class="col-md-4">
    <%= render "/likes/like" %>
  </div>
  <div class="col-md-4">
    <%= render "/favourites/favourite" %>
  </div>
  <div class="col-md-4">
    <% if user_signed_in? %>
      <% if current_user_vote.nil? %>
        <%= link_to fa_icon("chevron-up"),
                    question_votes_path(@question, {vote: {up: true}}),
                    class: "big-icon",
                    method: :post %>
        <%= link_to fa_icon("chevron-down"),
                    question_votes_path(@question, {vote: {up: false}}),
                    class: "big-icon",
                    method: :post %>
      <% elsif current_user_vote.up? %>
        <%# user has voted up %>
        <%= link_to fa_icon("chevron-circle-up"),
                    question_vote_path(@question, current_user_vote),
                    method: :delete,
                    class: "big-icon" %>
        <%= link_to fa_icon("chevron-down"),
                    question_vote_path(@question, current_user_vote, {vote: {up: false}}),
                    method: :patch,
                    class: "big-icon" %>
      <% else %>
        <%# user has voted down %>
        <%= link_to fa_icon("chevron-up"),
                    question_vote_path(@question, current_user_vote, {vote: {up: true}}),
                    method: :patch,
                    class: "big-icon" %>
        <%= link_to fa_icon("chevron-circle-down"),
                    question_vote_path(@question, current_user_vote),
                    method: :delete,
                    class: "big-icon" %>
      <% end %>
      (<%= @question.votes_count %>)
    <% end %>
  </div>
</div>
<div class="clearfix"></div>
<!-- <%= form_for @question do |f| %>
  <%= f.hidden_field :locked, value: !@question.locked %>
  <%= f.submit @question.locked ? "Lock" : "Un-lock", class: "btn btn-warning" %>
<% end %> -->


<!-- <% if @question.locked? %>
  <%= link_to "Un-Lock", lock_question_path(@question), method: :patch, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
<% else %>
  <%= link_to "Lock", lock_question_path(@question), method: :patch, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
<% end %> -->


<h2>New Answer</h2>
<%= render "/answers/form" %>
<h2>Answers</h2>
<div class="answers">
  <% @question.answers.latest_first.each do |ans| %>
    <%= render "/answers/answer", ans: ans %>
  <% end %>
</div>