config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create] do
    collection do
      get   :edit
      patch :update
    end
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  patch "/questions/:id/lock" => "questions#lock", as: :lock_question
  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  get "/hello" => "welcome#index"

  get "/contact" => "contact#index"
  post "/contact" => "contact#create"

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/hello/:name" => "welcome#hello", as: :greet

  get "/hello/:name/:city" => "welcome#hello", as: :full_greeting

  root "welcome#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :body, presence: {message: "Answer is required"},
                   # answer body is unique per question
                   uniqueness: {scope: :question_id}
  scope :latest_first, lambda { order("created_at DESC") }
  # def self.latest_first
  #   order("created_at DESC")
  # end

  def user_name
    if user
      user.full_name
    else
      "Anonymous"
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question        = Question.friendly.find params[:question_id]
    # @answer  = @question.answers.new(answer_params)
    @answer          = Answer.new answer_params
    @answer.question = @question
    @answer.user     = current_user
    # respond_to allows us to reposnd differently to different request types
    # for instance we can send or do different things whether the format
    # is HTML, JS, JSON, XML..etc
    respond_to do |format|
      if @answer.save
        AnswersMailer.delay(run_at: 5.minutes.from_now).notify_question_owner(@answer)
        format.html { redirect_to question_path(@question), notice: "Answer created!" }
        # calling render in Rails will looking for ACTION.FORMAT.TEMPLATE_LANGUAGE
        # if you specify a template name as a symbol to `render` it will redner
        # that template instead of the default one
        # so in this case it will be: create_success.js.erb
        format.js   { render :create_success }
      else
        # this will render show.html.erb within questions folder (in views)
        # we're choosing to use "render" in here because we want to display
        # the errors resulting from unsuccessful save of @answer. The errors
        # are attached to the @answer object and can be accessed in:
        # @answer.errors
        # using redirect makes a whole new request cycles so we lose the @answer
        # object
        format.html do
          flash[:alert] = "Answer wasn't created"
          render "/questions/show"
        end
        format.js   { render :create_failure }
      end
    end
  end
# comment
  def destroy
    @answer   = Answer.find params[:id]
    @question = Question.friendly.find params[:question_id]
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_path(@question), notice: "Answer deleted." }
      format.js   { render }
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<!-- @answer - 55
     dom_id(@answer) => answer_55
   -->
<div class="well" id="<%= dom_id(ans) %>">
  <%= ans.body %>
  <%# question_answer_path({question_id: @question, id: ans}) %>
  <%# question_answer_path(@question, ans) %>
  <%# [@question, ans] %>
  <%= link_to "Delete", question_answer_path(@question, ans), method: :delete,
              class: "btn btn-sm btn-danger",
              data: {confirm: "Are you sure?"},
              remote: true %>
  <p>Created by <%= ans.user_name %> on
                <%= formatted_date(ans.created_at) %></p>
  <h3>Add Comment</h3>
  <%= simple_form_for [ans, Comment.new] do |f| %>
    <%= f.input :body, input_html: {placeholder: "add comment here.."} %>
    <%= f.submit "Comment" %>
  <% end %>
    <% ans.comments.each do |com| %>
      <div class="well">
        <%= com.body %>
      </div>
    <% end %>
</div>

app/views/answers/_form.html.erb
<%# @answer (not persisted)    -> URL: answers_path         (CREATE) %>
<%# @answer (persisted (in DB) -> URL: answer_path(@answer) (UPDATE) %>
<%#= form_for @answer, url: question_answers_path(@question) do |f| %>
<%= simple_form_for [@question, @answer], remote: true do |f| %>
  <%= f.input :body %>
  <%= f.submit "Create Answer", class: "btn btn-primary" %>
<% end %>

app/views/answers/create_failure.js.erb
<%# j is a Rails helper method that escapses a string to make it work properly
    with Javascript, mainly by putting \ characters before all " characters %>
$("#new_answer").replaceWith("<%= j render 'form' %>");

app/views/answers/create_success.js.erb
$(".answers").prepend("<%= j render 'answer', ans: @answer %>");

<%# we need to re-instantiate the @answer variable in here becuase the @Answer
    variable references a record that has already been created in the database
    so the form will use PATCH and submit to the update action. We want the
    form to submit to the create action %>
<% @answer = Answer.new %>
$("#new_answer").replaceWith("<%= j render 'form' %>");

app/views/answers/destroy.js.erb
$("#<%= dom_id(@answer) %>").fadeOut();