config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create] do
    collection do
      get   :edit
      patch :update
    end
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  patch "/questions/:id/lock" => "questions#lock", as: :lock_question
  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  get "/hello" => "welcome#index"

  get "/contact" => "contact#index"
  post "/contact" => "contact#create"

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/hello/:name" => "welcome#hello", as: :greet

  get "/hello/:name/:city" => "welcome#hello", as: :full_greeting

  root "welcome#index"

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def create
    @name = params[:name]
    @email = params[:email]
    # render text: "Thank you for contacting us!"
    # render :create, layout: "application"
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/create.html.erb
<h1>Thank you for contacting us</h1>
<h2>Your Info:</h2>
<p>name: <%= @name %></p>
<p>email: <%= @email %></p>

app/views/contact/index.html.erb
<h1>Contact Us</h1>

<%= form_tag "/contact" do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </div>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  <%= submit_tag "Contact Us" %>
<% end %>
<!--
<form action="/contact" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="YpGmwUucMCNTbG71eVo3WHMkdqFwI/YtGgIm/xO9bvgC0lHj8i2RXc6spa45WECPF+AbDHRrBeLcqLCE6ODDHw==">
  <input type="submit" name="commit" value="Contact Us">
</form> -->

<h2>Playing with URLs</h2>
<%= hello_path %>
<%# /hello %>
<hr>
<%= hello_url %>
<%# http://localhost:3000/hello %>
<hr>
<%= greet_path({name: "Tam"}) %>
<%# /hello/Tam %>
<hr>
<%# this is a shortcut for the path above %>
<%= greet_path("Tam") %>
<%# /hello/Tam %>
<hr>
<%= greet_url({name: "Tam", city: "Burnaby"}) %>
<%# http://localhost:3000/hello/Tam?city=Burnaby %>
<hr>
<%= full_greeting_path("Tam", "Burnaby") %>