config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create] do
    collection do
      get   :edit
      patch :update
    end
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  patch "/questions/:id/lock" => "questions#lock", as: :lock_question
  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  get "/hello" => "welcome#index"

  get "/contact" => "contact#index"
  post "/contact" => "contact#create"

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/hello/:name" => "welcome#hello", as: :greet

  get "/hello/:name/:city" => "welcome#hello", as: :full_greeting

  root "welcome#index"

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Awesome Answers", root_path, class: "navbar-brand animated tada" %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Contact Us", contact_path, class: "my-link-class", style: "color:green" %></li>
        <li><%= link_to "Subscribe", subscribe_path %></li>
        <li><%= link_to "All Questions", questions_path %></li>
        <li><%= link_to "New Question", new_question_path %></li>
      </ul>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to edit_users_path do %>
              Hello <%= current_user.first_name %>
            <% end %>
        </li>
        <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_session_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome Answers - Special</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>